FROM python:3.8

COPY . /home/app

RUN pip install -r /home/app/Docker_Deployment_local/requirements.txt

                                                
#CMD python /home/app/SAT_images_to_array_automation_LANDSAT-5.py
